/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    PrivateTransfer: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AlreadyRegistered",
          type: "error",
        },
        {
          inputs: [],
          name: "AmountMustBePositive",
          type: "error",
        },
        {
          inputs: [],
          name: "ETHTransferFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "InsufficientContractBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "registered",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
          ],
          name: "InsufficientPool",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidCiphertextLength",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidProof",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidRecipients",
          type: "error",
        },
        {
          inputs: [],
          name: "LengthMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "MustDepositETH",
          type: "error",
        },
        {
          inputs: [],
          name: "NotRegistered",
          type: "error",
        },
        {
          inputs: [],
          name: "RecipientNotRegistered",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferAlreadyUsed",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "depositAmount",
              type: "uint256",
            },
          ],
          name: "Registered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address[]",
              name: "recipients",
              type: "address[]",
            },
          ],
          name: "Transferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawn",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "accounts",
          outputs: [
            {
              internalType: "bytes",
              name: "encryptedBalance",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "publicKey",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "isRegistered",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "pk",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "initialBalance",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "commitment",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "proofInputs",
              type: "bytes",
            },
          ],
          name: "register",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalDeposits",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalRegistered",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "recipients",
              type: "address[]",
            },
            {
              internalType: "bytes[]",
              name: "encBalanceToUpdateReceiver",
              type: "bytes[]",
            },
            {
              internalType: "bytes",
              name: "encTotal",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "commitment",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "proofInputs",
              type: "bytes",
            },
          ],
          name: "transfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "usedTransfers",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "encNewBalance",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "commitment",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "proofInputs",
              type: "bytes",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
