/**
 * DON'T MODIFY OR DELETE THIS SCRIPT (unless you know what you're doing)
 *
 * This script generates the file containing the contracts Abi definitions.
 * These definitions are used to derive the types needed in the custom scaffold-eth hooks, for example.
 * This script should run after `hardhat ignition deploy`.
 */

import * as fs from "fs";
import prettier from "prettier";

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

const IGNITION_DEPLOYMENTS_DIR = "./ignition/deployments";
const ARTIFACTS_DIR = "./artifacts";

function getChainDirectories() {
  if (!fs.existsSync(IGNITION_DEPLOYMENTS_DIR)) return [];
  return fs
    .readdirSync(IGNITION_DEPLOYMENTS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory() && d.name.startsWith("chain-"))
    .map(d => d.name);
}

function getArtifactForContract(contractName: string): { abi: any[]; sourceName: string } | null {
  // Walk artifacts/contracts looking for <ContractName>.json
  const contractsDir = `${ARTIFACTS_DIR}/contracts`;
  if (!fs.existsSync(contractsDir)) return null;

  for (const solFile of fs.readdirSync(contractsDir, { withFileTypes: true })) {
    if (!solFile.isDirectory()) continue;
    const artifactPath = `${contractsDir}/${solFile.name}/${contractName}.json`;
    if (fs.existsSync(artifactPath)) {
      const artifact = JSON.parse(fs.readFileSync(artifactPath).toString());
      return { abi: artifact.abi, sourceName: `contracts/${solFile.name}/${contractName}.sol` };
    }
  }
  return null;
}

function getActualSourcesForContract(sources: Record<string, any>, contractName: string) {
  for (const sourcePath of Object.keys(sources)) {
    const sourceName = sourcePath.split("/").pop()?.split(".sol")[0];
    if (sourceName === contractName) {
      const contractContent = sources[sourcePath].content as string;
      const regex = /contract\s+(\w+)\s+is\s+([^{}]+)\{/;
      const match = contractContent.match(regex);

      if (match) {
        const inheritancePart = match[2];
        const inheritedContracts = inheritancePart.split(",").map(contract => `${contract.trim()}.sol`);
        return inheritedContracts;
      }
      return [];
    }
  }
  return [];
}

function getInheritedFunctions(sources: Record<string, any>, contractName: string) {
  const actualSources = getActualSourcesForContract(sources, contractName);
  const inheritedFunctions = {} as Record<string, any>;

  for (const sourceContractName of actualSources) {
    const sourcePath = Object.keys(sources).find(key => key.includes(`/${sourceContractName}`));
    if (sourcePath) {
      const srcName = sourcePath.split("/").pop()?.split(".sol")[0];
      const artifactPath = `${ARTIFACTS_DIR}/${sourcePath}/${srcName}.json`;
      if (fs.existsSync(artifactPath)) {
        const { abi } = JSON.parse(fs.readFileSync(artifactPath).toString());
        for (const functionAbi of abi) {
          if (functionAbi.type === "function") {
            inheritedFunctions[functionAbi.name] = sourcePath;
          }
        }
      }
    }
  }

  return inheritedFunctions;
}

function getSourcesFromBuildInfo(contractName: string): Record<string, any> | null {
  const buildInfoDir = `${ARTIFACTS_DIR}/build-info`;
  if (!fs.existsSync(buildInfoDir)) return null;

  for (const file of fs.readdirSync(buildInfoDir)) {
    if (!file.endsWith(".json")) continue;
    try {
      const buildInfo = JSON.parse(fs.readFileSync(`${buildInfoDir}/${file}`).toString());
      // Check if this build-info contains our contract
      const outputSources = buildInfo?.output?.sources ?? {};
      const hasContract = Object.keys(outputSources).some(k => k.endsWith(`${contractName}.sol`));
      if (hasContract) {
        // Return a sources map: path -> { content }
        const inputSources = buildInfo?.input?.sources ?? {};
        return inputSources;
      }
    } catch {
      // skip malformed build info
    }
  }
  return null;
}

function getContractDataFromDeployments() {
  const output = {} as Record<string, any>;
  const chainDirs = getChainDirectories();

  for (const chainDir of chainDirs) {
    const chainId = chainDir.replace("chain-", "");
    const deployedAddressesPath = `${IGNITION_DEPLOYMENTS_DIR}/${chainDir}/deployed_addresses.json`;

    if (!fs.existsSync(deployedAddressesPath)) continue;

    const deployedAddresses: Record<string, string> = JSON.parse(fs.readFileSync(deployedAddressesPath).toString());

    const contracts = {} as Record<string, any>;

    for (const [futureId, address] of Object.entries(deployedAddresses)) {
      // futureId format: "ModuleName#ContractName"
      const contractName = futureId.split("#")[1];
      if (!contractName) continue;

      // Try to read the artifact from the ignition deployment folder first
      const ignitionArtifactPath = `${IGNITION_DEPLOYMENTS_DIR}/${chainDir}/artifacts/${futureId}.json`;
      let abi: any[] = [];

      if (fs.existsSync(ignitionArtifactPath)) {
        const artifact = JSON.parse(fs.readFileSync(ignitionArtifactPath).toString());
        abi = artifact.abi ?? [];
      } else {
        // Fall back to the build artifacts directory
        const buildArtifact = getArtifactForContract(contractName);
        abi = buildArtifact?.abi ?? [];
      }

      // Compute inherited functions from build-info sources
      const sources = getSourcesFromBuildInfo(contractName);
      const inheritedFunctions = sources ? getInheritedFunctions(sources, contractName) : {};

      contracts[contractName] = { address, abi, inheritedFunctions };
    }

    output[chainId] = contracts;
  }

  return output;
}

/**
 * Generates the TypeScript contract definition file based on the Ignition deployment output.
 * Call this after `hardhat ignition deploy`.
 */
export default async function generateTsAbis() {
  const TARGET_DIR = "../nextjs/contracts/";
  const allContractsData = getContractDataFromDeployments();

  const fileContent = Object.entries(allContractsData).reduce((content, [chainId, chainConfig]) => {
    return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(chainConfig, null, 2)},`;
  }, "");

  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR);
  }
  fs.writeFileSync(
    `${TARGET_DIR}deployedContracts.ts`,
    await prettier.format(
      `${generatedContractComment} import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract"; \n\n
 const deployedContracts = {${fileContent}} as const; \n\n export default deployedContracts satisfies GenericContractsDeclaration`,
      {
        parser: "typescript",
      },
    ),
  );

  console.log(`📝 Updated TypeScript contract definition file on ${TARGET_DIR}deployedContracts.ts`);
}
